**Лабораторна №2**

Завдання 2.3. Порівняння якості класифікаторів на прикладі класифікації сортів ірисів

КРОК 1. ЗАВАНТАЖЕННЯ ТА ВИВЧЕННЯ ДАНИХ

In [ ]:
# Імпортуємо набір даних Iris
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
# Виводимо ключі словника з даними
print('Ключі iris dataset: \n{}'.format(iris_dataset.keys()))

Ключі iris dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
# Виводимо частину опису датасету
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [ ]:
# Виводимо назви класів (відповідей)
print('Назви відповідей: {}'.format(iris_dataset['target_names']))

Назви відповідей: ['setosa' 'versicolor' 'virginica']


In [ ]:
# Виводимо назви ознак (характеристик)
print('Назви ознак: {}'.format(iris_dataset['feature_names']))

Назви ознак: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
# Виводимо тип об'єкта з ознаками
print('Тип масиву data: {}'.format(type(iris_dataset['data'])))

Тип масиву data: <class 'numpy.ndarray'>


In [ ]:
# Виводимо розмірність масиву з ознаками
print('Форма масиву data: {}'.format(iris_dataset['data'].shape))

Форма масиву data: (150, 4)


In [ ]:
# Виводимо перші 5 прикладів з даними
print('Перші п’ять рядків масиву data:\n{}'.format(iris_dataset['data'][:5]))

Перші п’ять рядків масиву data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
# Виводимо тип об'єкта з мітками класів
print('Тип масиву target: {}'.format(type(iris_dataset['target'])))

Тип масиву target: <class 'numpy.ndarray'>


In [ ]:
# Виводимо всі мітки класів
print('Відповіді: {}'.format(iris_dataset['target']))

Відповіді: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
